### ISSUE TITLE
Additional property name is not allowed

### ISSUE THREAD

**Issue by tikejhy** [DataDog/KubeHound#133]
```
 ./kubehound.sh backend-up
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string.
(root) Additional property name is not allowed
```

Package: `KubeHound_Darwin_arm64`
Device: `23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000 arm64`

**Comment by d0g0x01** [comment]
Can you check your system meets the requirements? https://github.com/DataDog/KubeHound#application Typically this issue is related to an old docker compose version

**Comment by christophetd** [comment]
FWIW I've experienced this issue on an old version of Docker Desktop for Mac. Upgrading my Docker client helped.

**Comment by d0g0x01** [comment]
Closing the issue as stale. Let us know if you have any further issues
