### ISSUE TITLE
Links are broken Readme

### ISSUE THREAD

**Issue by timscn** [DataDog/KubeHound#158]
**Describe the bug**
the below links are broken -

https://github.com/DataDog/KubeHound/blob/main/docs/application/Architecture.excalidraw
https://github.com/DataDog/KubeHound/blob/main/edges
https://github.com/DataDog/KubeHound/tree/main/docs/edges

**To Reproduce**
Steps to reproduce the behavior - just one example:
1.  Go to [README.md](https://github.com/DataDog/KubeHound/blob/main/README.md ) and under Quick Links section
2. Click on '[design canvas](https://github.com/DataDog/KubeHound/blob/main/docs/application/Architecture.excalidraw)'

**Expected behavior**
Should be an overview of the application architecture

**Screenshots**
<img width="1154" alt="image" src="https://github.com/DataDog/KubeHound/assets/24395957/60d1bcce-5222-4aa0-bede-3d0809e2dcc3">

**Additional context**
not critical - but considering you're switching it from inner-source to open-source, potentially less people could be interested in it

**Comment by edznux-dd** [comment]
Thanks for the report, i've open https://github.com/DataDog/KubeHound/pull/159 to fix this!
