### ISSUE TITLE
Python query data not working perfectly

### ISSUE THREAD

**Issue by Ant0in3bzh** [DataDog/KubeHound#168]
**Describe the bug**
Hi, I'm trying to make a simple query with the _gremlin_python_ package and it's not working well. 
I think in the gremlin_python package the implementation of _DataType.custom_  is not implemented yet, take a look here: [https://github.com/../gremlin-python/../graphbinaryV1.py](https://github.com/apache/tinkerpop/blob/master/gremlin-python/src/main/python/gremlin_python/structure/io/graphbinaryV1.py#L116). And you have to add its definition here : [https://github.com/../gremlin-python/../traversal.py](https://github.com/apache/tinkerpop/blob/master/gremlin-python/src/main/python/gremlin_python/process/traversal.py). I tried to create it on my own but without success. 
Is there another way in python to extract the data for this type of query, like in json,csv or yaml or any other format ? 

**To Reproduce**
1. I run this code : 
``` python
KH_QUERY = "kh.V().critical()"
c = Client("ws://127.0.0.1:8182/gremlin", "kh")
results = c.submit(KH_QUERY).all().result()
print(results)
``` 

2. And i encounter this issue : 
```bash
KeyError: <DataType.custom: 0>
``` 

**Expected behavior**
Result in list form or dict. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.4 LTS
 - Python : 3.10
 - Kubehound : 1.2.0

**Conclusion**

Maybe I need to create an issue in [https://github.com/apache/tinkerpop/tree/master](https://github.com/apache/tinkerpop/tree/master). But I think you're implementing things for Kubehound there, so maybe you'll answer my issue.

**Comment by d0g0x01** [comment]
I think your query is returning a gremlin traversal which python does not understand. If you want a map back,  can you try

```groovy
kh.V().critical().elementMap()
```

**Comment by Ant0in3bzh** [comment]
great, it works, thank you for your advice. May I ask where I can find the documentation on the rules element value?
For example i got this :
```bash
        "rules": "[API(batch)::R(cronjobs)::N()::V(get,list,update,watch), API(batch)::R(jobs)::N()::V(create,delete,get,list,patch,update,watch), API(batch)::R(cronjobs/status)::N()::V(update), API(batch)::R(cronjobs/finalizers)::N()::V(update), API()::R(pods)::N()::V(delete,list), API(,events.k8s.io)::R(events)::N()::V(create,patch,update)]",
```
I understand N = node, V maybe a vertex ?

**Comment by d0g0x01** [comment]
https://kubehound.io/reference/entities/permissionset/
https://github.com/DataDog/KubeHound/blob/main/pkg/kubehound/models/converter/graph.go#L160

(gremlin support for nested arrays is tricky so we have to flatten to a single string)

**Comment by Ant0in3bzh** [comment]
Thanks for the help
