### ISSUE TITLE
v2.1.0-rc1 missing docker-compose.ui.yaml inside linux tar gz

### ISSUE THREAD

**Issue by theoberthier** [DataDog/KubeHound#190]
Hello, in the latest version, you forgot docker-compose.ui.yaml in the tar archives, I saw it in KubeHound_Linux_x86_64.tar.gz.
Maybe it's same for another archives.

**Comment by jt-dd** [comment]
Thx for reporting it. No the file is missing. It was patched previously but has not been merged.
Will push the file on the new release tomorrow.

**Comment by jt-dd** [comment]
fix inr v2.1.0-rc2. Feel free to reopen if you are having still some issues.
