### ISSUE TITLE
missing the release notes for the two recent tags

### ISSUE THREAD

**Issue by chenrui333** [DataDog/KubeHound#275]
👋 looks like the github releases are missing for the two recent tags, 1.5.2 and 1.5.3, raise this issue for some awareness. Thanks!

relates to:
- https://github.com/Homebrew/homebrew-core/pull/191355
- https://github.com/Homebrew/homebrew-core/pull/190957

**Comment by chenrui333** [comment]
cc @jt-dd @Minosity-VR

**Comment by Minosity-VR** [comment]
Oh good catch, looks like we missed something.
Thanks a lot for pointing it out! I guess it is causing issues in homebrew? Sorry if it's the case 😓 
working on it

**Comment by Minosity-VR** [comment]
Done, we just forgot to push the releases from draft to latest.
Thanks again for reporting!

**Comment by stefanb** [comment]
Thank you!
